### ISSUE TITLE
求问用的windows版报这个错

### ISSUE THREAD

**Issue by wanghuisenior** [869413421/chatgpt-web#66]
{
    "code": 500,
    "data": null,
    "errorMsg": "Post \"https://api.openai.com/v1/chat/completions\": dial tcp 128.121.146.101:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
}
有代理，用代理可以访问chatgpt官网进行对话，但是执行windows版本对话请求返回这个错误信息，是代理的问题还是啥意思

**Comment by 869413421** [comment]
代理没有响应，代理的问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月10日 09:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [869413421/chatgpt-web] 求问用的windows版报这个错 (Issue #66) |

{
"code": 500,
"data": null,
"errorMsg": "Post "https://api.openai.com/v1/chat/completions\": dial tcp 128.121.146.101:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
}
有代理，用代理可以访问chatgpt官网进行对话，但是执行windows版本对话请求返回这个错误信息，是代理的问题还是啥意思

**Comment by wanghuisenior** [comment]
> 

{"code":500,"data":null,"errorMsg":"error, status code: 429, message: You exceeded your current quota, please check your plan and billing details."}   这个呢，  不是免费的吗，我看这个意思是需要付费？

**Comment by liuyes** [comment]
一样的错误，但是代理是可以直接访问https://api.openai.com/v1/chat/completions的

**Comment by 869413421** [comment]
> > 
> 
> {"code":500,"data":null,"errorMsg":"error, status code: 429, message: You exceeded your current quota, please check your plan and billing details."}   这个呢，  不是免费的吗，我看这个意思是需要付费？

只有18美元的免费额度，你这个账号没额度了，登录openai的后台可以查看。

**Comment by long45343** [comment]
> > > 
> > 
> > 
> > {"code":500,"data":null,"errorMsg":"error, status code: 429, message: You exceeded your current quota, please check your plan and billing details."}   这个呢，  不是免费的吗，我看这个意思是需要付费？
> 
> 只有18美元的免费额度，你这个账号没额度了，登录openai的后台可以查看。

但是我这里是上了我的账户之后没用过但是也报这个错
